version: 2.1
jobs:
  build:
    docker:
      - image: kazimuth2/baked_fluent_ci:0.1.0
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Nightly Test
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            cd baked_fluent && rustup run nightly cargo test --features full-nightly --color always -- --color always
      - run:
          name: Stable Test
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd baked_fluent && rustup run stable cargo test --features full --color always -- --color always
      - save_cache:
          key: project-cache
          paths:
            - "/usr/local/cargo"
            - "./target"
