version: 2.1
jobs:
  build:
    docker:
      - image: kazimuth2/baked_fluent_ci:0.1.0
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - save_cache:
          key: project-cache
          paths:
            - "/usr/local/cargo"
            - "./target"
