version: 2.1
jobs:
  build:
    docker:
      - image: kazimuth2/baked_fluent_ci:0.1.0
    steps:
      - checkout
      - restore_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
            echo -e "\e[32mFormatting passed.\e[0m"
      - run:
          name: Nightly Test
          command: |
            export TERM=xterm-color
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            cd baked_fluent && rustup run nightly cargo test --features full-nightly
      - run:
          name: Stable Test
          command: |
            export TERM=xterm-color
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            cd baked_fluent && rustup run stable cargo test --features full
      - save_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo"
            - "./target"
