[package]
authors = ["James Gilles <jhgilles@mit.edu>"]
edition = "2018"
name = "baked_fluent_codegen"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.29"
quote = "0.6.12"
syn = "0.15.33"
fluent-syntax = "0.9"
annotate-snippets = "0.5.0"